export enum AnchorTypes {
  bool = "Boolean",
  u8 = "Int",
  i8 = "Int",
  u16 = "Int",
  i16 = "Int",
  u32 = "Int",
  i32 = "Int",
  f32 = "Float",
  u64 = "Int",
  i64 = "Int",
  f64 = "Float",
  u128 = "BigInt",
  i128 = "BigInt",
  bytes = "Bytes",
  string = "String",
  publicKey = "String",
  IdlTypeDefined = "IdlTypeDefined",
  IdlTypeOption = "IdlTypeOption",
  IdlTypeCOption = "IdlTypeCOption",
  IdlTypeVec = "[]",
  IdlTypeArray = "[]",
}
